// @generated by scripts/generate-model-catalog.mjs — DO NOT EDIT BY HAND.
// Run `npm run models:generate` to refresh; `npm run models:check` verifies it in CI.
//
// Snapshot of the models.dev registry, used as the offline fallback for
// `model::catalog`'s live fetch. See the generator for why this is generated
// rather than hand-maintained.
// Registry snapshot taken: 2026-08-13

use super::catalog::CatalogModel;

/// models.dev provider `anthropic` — 10 tool-calling text models.
pub const ANTHROPIC_MODELS: &[CatalogModel] = &[
    CatalogModel {
        id: "claude-opus-5",
        name: "Claude Opus 5",
        context: 1000000,
        input_per_million: 5.0,
        output_per_million: 25.0,
    },
    CatalogModel {
        id: "claude-sonnet-5",
        name: "Claude Sonnet 5",
        context: 1000000,
        input_per_million: 2.0,
        output_per_million: 10.0,
    },
    CatalogModel {
        id: "claude-fable-5",
        name: "Claude Fable 5",
        context: 1000000,
        input_per_million: 10.0,
        output_per_million: 50.0,
    },
    CatalogModel {
        id: "claude-opus-4-8",
        name: "Claude Opus 4.8",
        context: 1000000,
        input_per_million: 5.0,
        output_per_million: 25.0,
    },
    CatalogModel {
        id: "claude-opus-4-7",
        name: "Claude Opus 4.7",
        context: 1000000,
        input_per_million: 5.0,
        output_per_million: 25.0,
    },
    CatalogModel {
        id: "claude-sonnet-4-6",
        name: "Claude Sonnet 4.6",
        context: 1000000,
        input_per_million: 3.0,
        output_per_million: 15.0,
    },
    CatalogModel {
        id: "claude-opus-4-6",
        name: "Claude Opus 4.6",
        context: 1000000,
        input_per_million: 5.0,
        output_per_million: 25.0,
    },
    CatalogModel {
        id: "claude-opus-4-5",
        name: "Claude Opus 4.5 (latest)",
        context: 200000,
        input_per_million: 5.0,
        output_per_million: 25.0,
    },
    CatalogModel {
        id: "claude-haiku-4-5",
        name: "Claude Haiku 4.5 (latest)",
        context: 200000,
        input_per_million: 1.0,
        output_per_million: 5.0,
    },
    CatalogModel {
        id: "claude-sonnet-4-5",
        name: "Claude Sonnet 4.5 (latest)",
        context: 1000000,
        input_per_million: 3.0,
        output_per_million: 15.0,
    },
];

/// models.dev provider `openai` — 10 tool-calling text models.
pub const OPENAI_MODELS: &[CatalogModel] = &[
    CatalogModel {
        id: "gpt-5.6",
        name: "GPT-5.6",
        context: 1050000,
        input_per_million: 4.0,
        output_per_million: 20.0,
    },
    CatalogModel {
        id: "gpt-5.6-luna",
        name: "GPT-5.6 Luna",
        context: 1050000,
        input_per_million: 0.2,
        output_per_million: 1.2,
    },
    CatalogModel {
        id: "gpt-5.6-sol",
        name: "GPT-5.6 Sol",
        context: 1050000,
        input_per_million: 4.0,
        output_per_million: 20.0,
    },
    CatalogModel {
        id: "gpt-5.6-terra",
        name: "GPT-5.6 Terra",
        context: 1050000,
        input_per_million: 2.0,
        output_per_million: 12.0,
    },
    CatalogModel {
        id: "gpt-5.5",
        name: "GPT-5.5",
        context: 1050000,
        input_per_million: 5.0,
        output_per_million: 30.0,
    },
    CatalogModel {
        id: "gpt-5.5-pro",
        name: "GPT-5.5 Pro",
        context: 1050000,
        input_per_million: 30.0,
        output_per_million: 180.0,
    },
    CatalogModel {
        id: "gpt-5.4-mini",
        name: "GPT-5.4 mini",
        context: 400000,
        input_per_million: 0.75,
        output_per_million: 4.5,
    },
    CatalogModel {
        id: "gpt-5.4-nano",
        name: "GPT-5.4 nano",
        context: 400000,
        input_per_million: 0.2,
        output_per_million: 1.25,
    },
    CatalogModel {
        id: "gpt-5.4",
        name: "GPT-5.4",
        context: 1050000,
        input_per_million: 2.5,
        output_per_million: 15.0,
    },
    CatalogModel {
        id: "gpt-5.4-pro",
        name: "GPT-5.4 Pro",
        context: 1050000,
        input_per_million: 30.0,
        output_per_million: 180.0,
    },
];

/// models.dev provider `google` — 10 tool-calling text models.
pub const GOOGLE_MODELS: &[CatalogModel] = &[
    CatalogModel {
        id: "gemini-3.7-flash",
        name: "Gemini 3.7 Flash",
        context: 1048576,
        input_per_million: 0.75,
        output_per_million: 3.75,
    },
    CatalogModel {
        id: "gemini-flash-latest",
        name: "Gemini Flash Latest",
        context: 1048576,
        input_per_million: 0.75,
        output_per_million: 3.75,
    },
    CatalogModel {
        id: "gemini-3.5-flash-lite",
        name: "Gemini 3.5 Flash Lite",
        context: 1048576,
        input_per_million: 0.3,
        output_per_million: 2.5,
    },
    CatalogModel {
        id: "gemini-3.6-flash",
        name: "Gemini 3.6 Flash",
        context: 1048576,
        input_per_million: 0.75,
        output_per_million: 3.75,
    },
    CatalogModel {
        id: "gemini-flash-lite-latest",
        name: "Gemini Flash-Lite Latest",
        context: 1048576,
        input_per_million: 0.3,
        output_per_million: 2.5,
    },
    CatalogModel {
        id: "gemini-3.5-flash",
        name: "Gemini 3.5 Flash",
        context: 1048576,
        input_per_million: 1.5,
        output_per_million: 9.0,
    },
    CatalogModel {
        id: "gemini-3.1-flash-lite",
        name: "Gemini 3.1 Flash Lite",
        context: 1048576,
        input_per_million: 0.25,
        output_per_million: 1.5,
    },
    CatalogModel {
        id: "gemini-robotics-er-1.6-preview",
        name: "Gemini Robotics-ER 1.6 Preview",
        context: 131072,
        input_per_million: 1.0,
        output_per_million: 5.0,
    },
    CatalogModel {
        id: "gemini-3.1-flash-lite-preview",
        name: "Gemini 3.1 Flash Lite Preview",
        context: 1048576,
        input_per_million: 0.25,
        output_per_million: 1.5,
    },
    CatalogModel {
        id: "gemini-3.1-pro-preview",
        name: "Gemini 3.1 Pro Preview",
        context: 1048576,
        input_per_million: 2.0,
        output_per_million: 12.0,
    },
];
